version: '3.9'

services:
  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data
      - ./backend/logs:/app/logs
      - ./backend/experiments:/app/experiments
    environment:
      - LOG_LEVEL=INFO

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "8501:8501"
    depends_on:
      - backend
